### PR TITLE
Update by oid feature

### PR DESCRIPTION
**Pull request by alexbyk**
How about to allow updates by oid (the same way as remove/find_one does)?

### CODE REVIEW

**Comment by kraih** [comment]
I've thought about this before, but never liked how it looks.

**Comment by alexbyk** [comment]
What's wrong with 'how it looks'? I see many lines in my app like 

``` perl
$coll->update({_id => $id}, {foo => 'bar'})
```

 and they look boring. 
`$coll->update($oid, {foo => bar})` looks more clear I think

**Comment by kraih** [comment]
It looks inconsistent, and your example is actually an argument against it. If you want to replace the whole document you're much better off just using `$collection->save($doc)`.

**Comment by alexbyk** [comment]
That could be an argument against such changes, but `save` creates a new document  if it doesn't exist in collection, while `update` does not do that by default. Because of that (if you don't want to create a new document, only make changes in existing one) you can't use `save` to replace the whole document .

Also `find_one($id)` and `remove($id)` methods behaviour differs from what mongoshell does, but that is not a problem.

**Comment by kraih** [comment]
It's actually more consistent this way, i just noticed that the `find_one` example looks just the same. https://github.com/kraih/mango/blob/93af525938c19551c4ec4e4de80b2f3db80582e7/lib/Mango/Collection.pm#L421

**Comment by alexbyk** [comment]
Thanks :thumbsup:

**Pull request closed without merging**
